package com.khmercalendar.ai

import com.khmercalendar.ai.tools.AiEventView
import com.khmercalendar.ai.tools.CalendarQuery
import com.khmercalendar.ai.tools.CalendarTools
import com.khmercalendar.core.khmer.KhmerNumerals
import com.khmercalendar.core.khmer.KhmerTerms
import com.khmercalendar.core.nlu.EventProposal
import com.khmercalendar.core.nlu.ExtractedFact
import com.khmercalendar.core.nlu.FactSource
import com.khmercalendar.core.nlu.KhmerLexicon
import com.khmercalendar.core.nlu.LongTextEventExtractor
import com.khmercalendar.core.nlu.NaturalLanguageEventParser
import com.khmercalendar.core.nlu.ProposalField
import com.khmercalendar.core.recurrence.Frequency
import com.khmercalendar.core.recurrence.RecurrenceRule
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime

/** How an answer was produced, so the UI can say so honestly. */
enum class AnswerSource {
    /** Exact arithmetic over the event table. No model involved. */
    RULES,

    /** Generated by the local model on this device. */
    LOCAL_MODEL,
}

sealed interface AssistantReply {
    val source: AnswerSource

    /** A proposed event for the user to confirm; nothing is written until they do. */
    data class Draft(
        val proposal: EventProposal,
        val clashes: List<AiEventView>,
        override val source: AnswerSource,
    ) : AssistantReply

    data class Text(val text: String, override val source: AnswerSource) : AssistantReply

    data class Failure(val message: String) : AssistantReply {
        override val source = AnswerSource.RULES
    }
}

/**
 * The assistant.
 *
 * Two rules shape this class.
 *
 * **Rules before the model.** [NaturalLanguageEventParser] handles the phrasings people
 * actually type, in microseconds, with no memory cost and no way to invent a date. Summaries,
 * clash detection and free-slot search are arithmetic. The model is asked only for what
 * genuinely needs language. The practical result is that every feature below works with the
 * AI switched off and no model installed, which is what makes this usable on a mid-range
 * phone.
 *
 * **Nothing is written without confirmation.** Event creation returns a
 * [AssistantReply.Draft]; the caller shows it and the user accepts it.
 */
class AiAssistant(
    private val engine: AiEngine,
    private val calendar: CalendarQuery,
    private val parser: NaturalLanguageEventParser = NaturalLanguageEventParser(),
    private val extractor: LongTextEventExtractor = LongTextEventExtractor(parser),
    /**
     * The hours the user says they are available, read fresh on every call.
     *
     * A supplier rather than a value because the setting changes while the app is running and
     * a captured copy would answer with the old one. This module cannot see DataStore; the
     * app module passes a lambda that can.
     */
    private val availability: () -> ClosedRange<LocalTime> = { DEFAULT_AVAILABILITY },
) {

    val modelReady: Boolean get() = engine.isReady

    /**
     * Turns text into a proposed event.
     *
     * Handles both a one-line command ("ថ្ងៃស្អែកម៉ោង ២ រសៀល ប្រជុំជាមួយក្រុមការងារ") and a whole
     * pasted announcement, because users do both and the difference is not something they
     * should have to declare. [LongTextEventExtractor] segments the input, finds the sentence
     * that is actually announcing something, and builds a short title around the event noun
     * in it - so a pasted paragraph produces "កិច្ចប្រជុំប្រចាំសប្តាហ៍" rather than the paragraph.
     *
     * The model is asked only when the rules find nothing, and its answer is validated the
     * same way. Neither path may invent: a value the text did not state comes back null and
     * named in [EventProposal.missing].
     */
    suspend fun proposeEvent(text: String, now: LocalDateTime = LocalDateTime.now()): AssistantReply {
        val trimmed = text.trim()
        if (trimmed.isEmpty()) {
            return AssistantReply.Failure("សូមបញ្ចូលអត្ថបទជាមុនសិន")
        }

        // runCatching, not because a failure is expected, but because this is the one place
        // user-supplied text of arbitrary shape meets the parser: a crash here would take
        // the calendar with it, and the whole design says it must not.
        val extracted = runCatching { extractor.extract(trimmed, now) }.getOrNull()
        if (extracted != null && extracted.confidence >= MIN_RULE_CONFIDENCE) {
            return withClashes(extracted, AnswerSource.RULES, now)
        }

        if (!engine.isReady) {
            // Even a low-confidence rule result beats nothing: it is at least drawn from the
            // user's own words, and they confirm it before anything is saved.
            extracted?.let { return withClashes(it, AnswerSource.RULES, now) }
            return AssistantReply.Failure(
                "មិនអាចយល់សំណើនេះទេ។ សូមសរសេរកាលបរិច្ឆេទ និងម៉ោង " +
                    "ឧទាហរណ៍ «ស្អែក ម៉ោង ២ រសៀល ប្រជុំ»",
            )
        }

        val prompt = extractionPrompt(condenseForModel(trimmed), now)
        val raw = engine.generate(prompt, maxTokens = 320).getOrElse {
            extracted?.let { fallback -> return withClashes(fallback, AnswerSource.RULES, now) }
            return AssistantReply.Failure("គំរូ AI មិនអាចដំណើរការបានទេ")
        }
        val fromModel = runCatching { parseModelJson(raw, now) }.getOrNull()
            ?: extracted
            ?: return AssistantReply.Failure("មិនអាចបង្កើតព្រឹត្តិការណ៍ពីអត្ថបទនេះទេ")
        return withClashes(fromModel, AnswerSource.LOCAL_MODEL, now)
    }

    /**
     * Shortens text before it reaches the model.
     *
     * A small model given three thousand characters spends its whole context on them and
     * answers worse than it would on the relevant paragraph. The rule extractor has already
     * located the announcing region, so the model is given a bounded window rather than the
     * document - which also keeps inference on a mid-range phone to a few seconds.
     */
    internal fun condenseForModel(text: String): String {
        if (text.length <= MODEL_INPUT_BUDGET) return text
        val sentences = text.split(Regex("(?<=[។!?])|\n+"))
            .map { it.trim() }
            .filter { it.isNotEmpty() }
        val ranked = sentences.sortedByDescending { sentence ->
            val lower = KhmerNumerals.toAscii(sentence).lowercase()
            var score = 0
            if (KhmerLexicon.EVENT_NOUNS.any { lower.contains(it.lowercase()) }) score += 4
            if (KhmerLexicon.RELATIVE_DAYS.keys.any { lower.contains(it) }) score += 3
            if (KhmerLexicon.WEEKDAYS.keys.any { lower.contains(it) }) score += 3
            if (KhmerLexicon.HOUR_MARKERS.any { lower.contains(it) }) score += 3
            score
        }
        val kept = StringBuilder()
        for (sentence in ranked) {
            if (kept.length + sentence.length > MODEL_INPUT_BUDGET) break
            kept.append(sentence).append(' ')
        }
        return kept.toString().trim().ifBlank { text.take(MODEL_INPUT_BUDGET) }
    }

    /** Everything in the next [days] days, summarised exactly. */
    suspend fun summarizeUpcoming(days: Int = 7, now: LocalDateTime = LocalDateTime.now()): AssistantReply {
        val events = calendar.eventsBetween(now, now.plusDays(days.toLong()))
        if (events.isEmpty()) {
            return AssistantReply.Text(
                "គ្មានព្រឹត្តិការណ៍ក្នុងរយៈពេល ${KhmerNumerals.toKhmer(days)} ថ្ងៃខាងមុខទេ។",
                AnswerSource.RULES,
            )
        }
        val byDay = events.groupBy { it.start.toLocalDate() }.toSortedMap()
        val text = buildString {
            append("ព្រឹត្តិការណ៍ ${KhmerNumerals.toKhmer(events.size)} ក្នុងរយៈពេល ")
            append("${KhmerNumerals.toKhmer(days)} ថ្ងៃខាងមុខ៖\n\n")
            byDay.forEach { (day, list) ->
                append(CalendarTools.describeDay(day, list)).append("\n\n")
            }
        }.trim()
        return AssistantReply.Text(text, AnswerSource.RULES)
    }

    /** Overlapping events in a window, found exactly. */
    suspend fun findConflicts(days: Int = 30, now: LocalDateTime = LocalDateTime.now()): AssistantReply {
        val events = calendar.eventsBetween(now, now.plusDays(days.toLong()))
        val conflicts = CalendarTools.conflicts(events)
        if (conflicts.isEmpty()) {
            return AssistantReply.Text("រកមិនឃើញការជាន់គ្នានៃព្រឹត្តិការណ៍ទេ។", AnswerSource.RULES)
        }
        val text = buildString {
            append("រកឃើញការជាន់គ្នា ${KhmerNumerals.toKhmer(conflicts.size)}៖\n\n")
            conflicts.forEach { c ->
                append("• ${c.a.title} ⟷ ${c.b.title}\n")
                append("  ${khmerDate(c.a.start.toLocalDate())} — ជាន់គ្នា ${KhmerNumerals.toKhmer(c.overlapMinutes.toInt())} នាទី\n")
            }
        }.trim()
        return AssistantReply.Text(text, AnswerSource.RULES)
    }

    /** Free time on a day, computed from the event table. */
    suspend fun suggestFreeSlots(
        date: LocalDate,
        minimumMinutes: Long = 60,
        now: LocalDateTime = LocalDateTime.now(),
    ): AssistantReply {
        val events = calendar.eventsBetween(
            LocalDateTime.of(date, LocalTime.MIN),
            LocalDateTime.of(date, LocalTime.MAX),
        )
        val window = availability()
        val slots = CalendarTools.freeSlots(
            events = events,
            date = date,
            minimumMinutes = minimumMinutes,
            dayStart = window.start,
            dayEnd = window.endInclusive,
            // Asked about today, the answer must not open with hours already gone.
            notBefore = now,
        )
        if (slots.isEmpty()) {
            val exhausted = date == now.toLocalDate() &&
                !now.toLocalTime().isBefore(window.endInclusive)
            return AssistantReply.Text(
                if (exhausted) {
                    "ម៉ោងទំនេររបស់ថ្ងៃនេះបានកន្លងផុតហើយ។"
                } else {
                    "គ្មានពេលទំនេរគ្រប់គ្រាន់ទេ។"
                },
                AnswerSource.RULES,
            )
        }
        val text = buildString {
            append("ពេលទំនេរនៅ${khmerDate(date)}៖\n")
            slots.forEach { s ->
                append("• ").append(KhmerNumerals.toKhmer("%02d:%02d".format(s.start.hour, s.start.minute)))
                append(" – ").append(KhmerNumerals.toKhmer("%02d:%02d".format(s.end.hour, s.end.minute)))
                append(" (").append(KhmerNumerals.toKhmer(s.minutes.toInt())).append(" នាទី)\n")
            }
        }.trim()
        return AssistantReply.Text(text, AnswerSource.RULES)
    }

    /**
     * A free-form question about the user's own calendar.
     *
     * The only path that requires a model. The relevant events are put in the prompt and the
     * answer is generated on the device; nothing is sent anywhere.
     */
    fun ask(question: String, now: LocalDateTime = LocalDateTime.now()): Flow<String> = flow {
        if (!engine.isReady) {
            emit("សូមបើកមុខងារ AI និងដំឡើងគំរូជាមុនសិន។")
            return@flow
        }
        val events = calendar.eventsBetween(now.minusDays(7), now.plusDays(60))
        val prompt = questionPrompt(question, events, now)
        engine.generateStream(prompt, maxTokens = 384).collect { emit(it) }
    }

    // ---------------------------------------------------------------------------------

    /**
     * Attaches any events the proposal would collide with.
     *
     * A proposal with no date cannot clash with anything, and a proposal with no time is an
     * all-day entry that is checked across the whole day rather than an hour of it.
     */
    private suspend fun withClashes(
        proposal: EventProposal,
        source: AnswerSource,
        now: LocalDateTime,
    ): AssistantReply {
        val date = proposal.date
            ?: return AssistantReply.Draft(proposal, emptyList(), source)

        val start = proposal.startTime?.let { LocalDateTime.of(date, it) } ?: date.atStartOfDay()
        val end = proposal.endTime?.let { LocalDateTime.of(date, it) }
            ?: if (proposal.startTime == null) date.plusDays(1).atStartOfDay() else start.plusHours(1)

        val sameWindow = runCatching {
            calendar.eventsBetween(start.minusHours(12), end.plusHours(12))
        }.getOrDefault(emptyList())

        return AssistantReply.Draft(
            proposal = proposal,
            clashes = CalendarTools.clashesWith(sameWindow, start, end),
            source = source,
        )
    }

    private fun extractionPrompt(text: String, now: LocalDateTime): String = """
        You extract ONE calendar event from a Khmer or English message.
        Today is ${now.toLocalDate()} (${now.dayOfWeek}), the time is ${now.toLocalTime().withSecond(0).withNano(0)}.

        Rules:
        - Reply with JSON only. No explanation, no markdown.
        - "title" must be a SHORT name for the event, at most 8 words. Never copy the whole
          message into the title. Summarise it.
        - Use null for anything the message does not state. NEVER invent a date, a time, a
          place or a person. A missing time must be null, not a guess.
        - Put remaining context in "description", not in the title.
        - Keep the text in the language the user wrote.

        Shape:
        {"title":"","date":"YYYY-MM-DD","startTime":"HH:MM","endTime":"HH:MM",
         "location":null,"description":null,"participants":[],"repeat":null,"remindMinutes":[]}

        "repeat" is one of null, "DAILY", "WEEKLY", "MONTHLY", "YEARLY".

        Message: $text
    """.trimIndent()

    private fun questionPrompt(question: String, events: List<AiEventView>, now: LocalDateTime): String = """
        You answer questions about the user's own calendar. Today is ${now.toLocalDate()}.
        Answer briefly, in the language of the question. Use only the events listed; if the
        answer is not among them, say you cannot find it.

        Events:
        ${CalendarTools.contextBlock(events)}

        Question: $question
        Answer:
    """.trimIndent()

    /**
     * Reads the model's JSON, tolerating the prose small models like to wrap it in.
     *
     * Everything is validated rather than trusted: a model that returns a start after its
     * end, or a date it invented, produces no draft at all rather than a wrong entry in
     * someone's calendar.
     */
    internal fun parseModelJson(raw: String, now: LocalDateTime): EventProposal? {
        val json = raw.substringAfter('{', "").substringBeforeLast('}', "")
            .let { if (it.isBlank()) return null else "{$it}" }

        fun field(name: String): String? =
            Regex("\"$name\"\\s*:\\s*\"([^\"]*)\"").find(json)
                ?.groupValues?.get(1)
                ?.trim()
                ?.takeIf { it.isNotBlank() && !it.equals("null", ignoreCase = true) }

        // A title is the one thing a proposal cannot do without, and a model that returns the
        // whole message as its title has failed the instruction; cap it rather than accept it.
        val title = field("title")?.let { capTitle(it) } ?: return null
        val date = field("date")?.let { parseDate(it) } ?: return null

        // A date the model placed years away has almost certainly been misread.
        if (date.isBefore(now.toLocalDate().minusYears(1)) ||
            date.isAfter(now.toLocalDate().plusYears(5))
        ) {
            return null
        }

        val startTime = field("startTime")?.let { parseTimeOfDay(it) }
        val endTime = field("endTime")?.let { parseTimeOfDay(it) }
            ?.takeIf { startTime == null || it.isAfter(startTime) }

        val repeat = field("repeat")?.uppercase()
            ?.let { r -> Frequency.entries.firstOrNull { it.name == r } }
            ?.let { RecurrenceRule(it) }

        val reminders = Regex("\"remindMinutes\"\\s*:\\s*\\[([^]]*)]").find(json)
            ?.groupValues?.get(1).orEmpty()
            .split(',').mapNotNull { it.trim().toIntOrNull() }.filter { it in 0..40_320 }

        val participants = Regex("\"participants\"\\s*:\\s*\\[([^]]*)]").find(json)
            ?.groupValues?.get(1).orEmpty()
            .split(',')
            .mapNotNull { it.trim().trim('"').takeIf { p -> p.isNotBlank() } }
            .take(10)

        val missing = buildList {
            if (startTime == null) add(ProposalField.START_TIME)
            if (field("location") == null) add(ProposalField.LOCATION)
            if (reminders.isEmpty()) add(ProposalField.REMINDER)
        }

        val facts = buildList {
            add(ExtractedFact(ProposalField.TITLE, title, FactSource.INFERRED))
            add(ExtractedFact(ProposalField.DATE, date.toString(), FactSource.EXPLICIT))
            startTime?.let {
                add(ExtractedFact(ProposalField.START_TIME, it.toString(), FactSource.EXPLICIT))
            }
        }

        return EventProposal(
            title = title,
            date = date,
            startTime = startTime,
            endTime = endTime,
            durationMinutes = if (startTime != null && endTime != null) {
                java.time.Duration.between(startTime, endTime).toMinutes().toInt()
            } else {
                null
            },
            location = field("location"),
            description = field("description"),
            participants = participants,
            recurrence = repeat,
            reminderMinutes = reminders,
            confidence = 0.6f,
            facts = facts,
            missing = missing,
            fromModel = true,
        )
    }

    /** Keeps a model title to a name, however much it wanted to write. */
    private fun capTitle(raw: String): String {
        val words = raw.trim().split(Regex("\\s+")).filter { it.isNotBlank() }
        return words.take(MODEL_TITLE_MAX_WORDS).joinToString(" ").take(80)
    }

    private fun parseDate(value: String): LocalDate? =
        runCatching { LocalDate.parse(value.take(10)) }.getOrNull()

    private fun parseTimeOfDay(value: String): LocalTime? =
        runCatching { LocalTime.parse(value.trim().take(5)) }.getOrNull()

    /**
     * A date inside a Khmer sentence.
     *
     * The clash and free-time replies used to interpolate a [LocalDate] directly, which
     * renders as "2026-09-08" - an ISO date dropped into the middle of a line that is
     * otherwise entirely Khmer, with Latin digits even for a user who has asked for Khmer
     * numerals everywhere else.
     */
    private fun khmerDate(date: LocalDate): String = buildString {
        append("ថ្ងៃ").append(KhmerTerms.dayOfWeek(date.dayOfWeek))
        append(" ទី").append(KhmerNumerals.toKhmer(date.dayOfMonth))
        append(" ខែ").append(KhmerTerms.solarMonth(date.monthValue))
    }

    companion object {
        /** Below this the model is asked, if one is loaded. */
        const val MIN_RULE_CONFIDENCE = 0.55f

        /** Characters of context the model is given. Beyond it, the text is condensed. */
        const val MODEL_INPUT_BUDGET = 1_200

        private const val MODEL_TITLE_MAX_WORDS = 8

        /** Matches [com.khmercalendar.data.prefs.AppSettings] so a test sees the real default. */
        val DEFAULT_AVAILABILITY: ClosedRange<LocalTime> = LocalTime.of(8, 0)..LocalTime.of(18, 0)
    }
}
