package com.khmercalendar.ai

import com.khmercalendar.ai.tools.AiEventView
import com.khmercalendar.ai.tools.CalendarQuery
import com.khmercalendar.ai.tools.CalendarTools
import com.khmercalendar.core.khmer.KhmerNumerals
import com.khmercalendar.core.nlu.EventDraft
import com.khmercalendar.core.nlu.NaturalLanguageEventParser
import com.khmercalendar.core.recurrence.Frequency
import com.khmercalendar.core.recurrence.RecurrenceRule
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.format.DateTimeParseException

/** How an answer was produced, so the UI can say so honestly. */
enum class AnswerSource {
    /** Exact arithmetic over the event table. No model involved. */
    RULES,

    /** Generated by the local model on this device. */
    LOCAL_MODEL,
}

sealed interface AssistantReply {
    val source: AnswerSource

    /** A proposed event for the user to confirm; nothing is written until they do. */
    data class Draft(
        val draft: EventDraft,
        val clashes: List<AiEventView>,
        override val source: AnswerSource,
    ) : AssistantReply

    data class Text(val text: String, override val source: AnswerSource) : AssistantReply

    data class Failure(val message: String) : AssistantReply {
        override val source = AnswerSource.RULES
    }
}

/**
 * The assistant.
 *
 * Two rules shape this class.
 *
 * **Rules before the model.** [NaturalLanguageEventParser] handles the phrasings people
 * actually type, in microseconds, with no memory cost and no way to invent a date. Summaries,
 * clash detection and free-slot search are arithmetic. The model is asked only for what
 * genuinely needs language. The practical result is that every feature below works with the
 * AI switched off and no model installed, which is what makes this usable on a mid-range
 * phone.
 *
 * **Nothing is written without confirmation.** Event creation returns a
 * [AssistantReply.Draft]; the caller shows it and the user accepts it.
 */
class AiAssistant(
    private val engine: AiEngine,
    private val calendar: CalendarQuery,
    private val parser: NaturalLanguageEventParser = NaturalLanguageEventParser(),
) {

    val modelReady: Boolean get() = engine.isReady

    /**
     * Turns a request such as "ថ្ងៃស្អែកម៉ោង ២ រសៀល ប្រជុំជាមួយក្រុមការងារ" into a proposed event.
     */
    suspend fun proposeEvent(text: String, now: LocalDateTime = LocalDateTime.now()): AssistantReply {
        parser.parse(text, now)
            ?.takeIf { it.confidence >= NaturalLanguageEventParser.MIN_CONFIDENCE }
            ?.let { return withClashes(it, AnswerSource.RULES) }

        if (!engine.isReady) {
            return AssistantReply.Failure(
                "មិនអាចយល់សំណើនេះទេ។ សូមសរសេរកាលបរិច្ឆេទ និងម៉ោង ឧទាហរណ៍ «ស្អែក ម៉ោង ២ រសៀល ប្រជុំ»"
            )
        }

        val prompt = extractionPrompt(text, now)
        val raw = engine.generate(prompt, maxTokens = 256).getOrElse {
            return AssistantReply.Failure("គំរូ AI មិនអាចដំណើរការបានទេ")
        }
        val draft = parseModelJson(raw, now)
            ?: return AssistantReply.Failure("មិនអាចបង្កើតព្រឹត្តិការណ៍ពីអត្ថបទនេះទេ")
        return withClashes(draft, AnswerSource.LOCAL_MODEL)
    }

    /** Everything in the next [days] days, summarised exactly. */
    suspend fun summarizeUpcoming(days: Int = 7, now: LocalDateTime = LocalDateTime.now()): AssistantReply {
        val events = calendar.eventsBetween(now, now.plusDays(days.toLong()))
        if (events.isEmpty()) {
            return AssistantReply.Text(
                "គ្មានព្រឹត្តិការណ៍ក្នុងរយៈពេល ${KhmerNumerals.toKhmer(days)} ថ្ងៃខាងមុខទេ។",
                AnswerSource.RULES,
            )
        }
        val byDay = events.groupBy { it.start.toLocalDate() }.toSortedMap()
        val text = buildString {
            append("ព្រឹត្តិការណ៍ ${KhmerNumerals.toKhmer(events.size)} ក្នុងរយៈពេល ")
            append("${KhmerNumerals.toKhmer(days)} ថ្ងៃខាងមុខ៖\n\n")
            byDay.forEach { (day, list) ->
                append(CalendarTools.describeDay(day, list)).append("\n\n")
            }
        }.trim()
        return AssistantReply.Text(text, AnswerSource.RULES)
    }

    /** Overlapping events in a window, found exactly. */
    suspend fun findConflicts(days: Int = 30, now: LocalDateTime = LocalDateTime.now()): AssistantReply {
        val events = calendar.eventsBetween(now, now.plusDays(days.toLong()))
        val conflicts = CalendarTools.conflicts(events)
        if (conflicts.isEmpty()) {
            return AssistantReply.Text("រកមិនឃើញការជាន់គ្នានៃព្រឹត្តិការណ៍ទេ។", AnswerSource.RULES)
        }
        val text = buildString {
            append("រកឃើញការជាន់គ្នា ${KhmerNumerals.toKhmer(conflicts.size)}៖\n\n")
            conflicts.forEach { c ->
                append("• ${c.a.title} ⟷ ${c.b.title}\n")
                append("  ${c.a.start.toLocalDate()} — ជាន់គ្នា ${KhmerNumerals.toKhmer(c.overlapMinutes.toInt())} នាទី\n")
            }
        }.trim()
        return AssistantReply.Text(text, AnswerSource.RULES)
    }

    /** Free time on a day, computed from the event table. */
    suspend fun suggestFreeSlots(date: LocalDate, minimumMinutes: Long = 60): AssistantReply {
        val events = calendar.eventsBetween(
            LocalDateTime.of(date, LocalTime.MIN),
            LocalDateTime.of(date, LocalTime.MAX),
        )
        val slots = CalendarTools.freeSlots(events, date, minimumMinutes)
        if (slots.isEmpty()) {
            return AssistantReply.Text("ថ្ងៃនេះគ្មានពេលទំនេរគ្រប់គ្រាន់ទេ។", AnswerSource.RULES)
        }
        val text = buildString {
            append("ពេលទំនេរនៅថ្ងៃ $date៖\n")
            slots.forEach { s ->
                append("• ").append(KhmerNumerals.toKhmer("%02d:%02d".format(s.start.hour, s.start.minute)))
                append(" – ").append(KhmerNumerals.toKhmer("%02d:%02d".format(s.end.hour, s.end.minute)))
                append(" (").append(KhmerNumerals.toKhmer(s.minutes.toInt())).append(" នាទី)\n")
            }
        }.trim()
        return AssistantReply.Text(text, AnswerSource.RULES)
    }

    /**
     * A free-form question about the user's own calendar.
     *
     * The only path that requires a model. The relevant events are put in the prompt and the
     * answer is generated on the device; nothing is sent anywhere.
     */
    fun ask(question: String, now: LocalDateTime = LocalDateTime.now()): Flow<String> = flow {
        if (!engine.isReady) {
            emit("សូមបើកមុខងារ AI និងដំឡើងគំរូជាមុនសិន។")
            return@flow
        }
        val events = calendar.eventsBetween(now.minusDays(7), now.plusDays(60))
        val prompt = questionPrompt(question, events, now)
        engine.generateStream(prompt, maxTokens = 384).collect { emit(it) }
    }

    // ---------------------------------------------------------------------------------

    private suspend fun withClashes(draft: EventDraft, source: AnswerSource): AssistantReply {
        val sameWindow = calendar.eventsBetween(draft.start.minusHours(12), draft.end.plusHours(12))
        return AssistantReply.Draft(
            draft = draft,
            clashes = CalendarTools.clashesWith(sameWindow, draft.start, draft.end),
            source = source,
        )
    }

    private fun extractionPrompt(text: String, now: LocalDateTime): String = """
        You convert a Khmer or English request into one calendar event.
        Today is ${now.toLocalDate()} (${now.dayOfWeek}), the time is ${now.toLocalTime().withSecond(0).withNano(0)}.
        Reply with JSON only, no explanation, in exactly this shape:
        {"title":"","start":"YYYY-MM-DDTHH:MM","end":"YYYY-MM-DDTHH:MM","allDay":false,"location":null,"repeat":null,"remindMinutes":[]}
        "repeat" is one of null, "DAILY", "WEEKLY", "MONTHLY", "YEARLY".
        Keep the title in the language the user wrote it in.

        Request: $text
    """.trimIndent()

    private fun questionPrompt(question: String, events: List<AiEventView>, now: LocalDateTime): String = """
        You answer questions about the user's own calendar. Today is ${now.toLocalDate()}.
        Answer briefly, in the language of the question. Use only the events listed; if the
        answer is not among them, say you cannot find it.

        Events:
        ${CalendarTools.contextBlock(events)}

        Question: $question
        Answer:
    """.trimIndent()

    /**
     * Reads the model's JSON, tolerating the prose small models like to wrap it in.
     *
     * Everything is validated rather than trusted: a model that returns a start after its
     * end, or a date it invented, produces no draft at all rather than a wrong entry in
     * someone's calendar.
     */
    internal fun parseModelJson(raw: String, now: LocalDateTime): EventDraft? {
        val json = raw.substringAfter('{', "").substringBeforeLast('}', "")
            .let { if (it.isBlank()) return null else "{$it}" }

        fun field(name: String): String? =
            Regex("\"$name\"\\s*:\\s*\"([^\"]*)\"").find(json)?.groupValues?.get(1)?.takeIf { it.isNotBlank() }

        val title = field("title") ?: return null
        val start = field("start")?.let { parseDateTime(it) } ?: return null
        val allDay = Regex("\"allDay\"\\s*:\\s*true").containsMatchIn(json)
        val end = field("end")?.let { parseDateTime(it) }
            ?: if (allDay) start.plusDays(1) else start.plusHours(1)
        if (!end.isAfter(start)) return null
        // A model that proposes something years away has almost certainly misread the date.
        if (start.isBefore(now.minusYears(1)) || start.isAfter(now.plusYears(5))) return null

        val repeat = field("repeat")?.uppercase()?.let { r ->
            Frequency.entries.firstOrNull { it.name == r }
        }?.let { RecurrenceRule(it) }

        val reminders = Regex("\"remindMinutes\"\\s*:\\s*\\[([^]]*)]").find(json)
            ?.groupValues?.get(1).orEmpty()
            .split(',').mapNotNull { it.trim().toIntOrNull() }.filter { it in 0..40_320 }

        return EventDraft(
            title = title.trim(),
            start = start,
            end = end,
            allDay = allDay,
            location = field("location"),
            recurrence = repeat,
            reminderMinutes = reminders,
            confidence = 0.6f,
            explanation = "បង្កើតដោយគំរូ AI ក្នុងឧបករណ៍",
        )
    }

    private fun parseDateTime(value: String): LocalDateTime? = try {
        when {
            value.contains('T') -> LocalDateTime.parse(value.take(16))
            else -> LocalDate.parse(value.take(10)).atStartOfDay()
        }
    } catch (_: DateTimeParseException) {
        null
    }
}
